on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: extractions/setup-just@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_command: export CGO_ENABLED=0
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "./go.mod"
